server:
  port: 8081
  
spring:
  application:
    name: 'fornecedor'
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888
   
# CONFIGURA EUREKA CLIENTE
eureka:
  client:
    fetch-registry: true 
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka